/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JOptionPane;
import logica.LogicaElectoral;
import modelo.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Sebas
 */
public class frmConfigurarEleccion extends javax.swing.JFrame {
    private LogicaElectoral motor;

    /**
     * Creates new form frmConfigurarEleccion
     */
    public frmConfigurarEleccion(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        this.setLocationRelativeTo(null); 
        LocalDate fechaActual = LocalDate.now();
        txtFecha.setText(fechaActual.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtFecha.setEditable(false);
        
        llenarComboTipoEleccion();
        configurarInterfazInicial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cmbTipoEleccion = new javax.swing.JComboBox<>();
        btnGuardarConfig = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo");

        jLabel2.setText("Fecha");

        jLabel4.setText("Tipo de Eleccion");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        cmbTipoEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEleccionActionPerformed(evt);
            }
        });

        btnGuardarConfig.setText("Confirmar Eleccion");
        btnGuardarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConfigActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addComponent(cmbTipoEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btnVolver)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarConfig)
                    .addComponent(btnVolver))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void cmbTipoEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEleccionActionPerformed
    
    }//GEN-LAST:event_cmbTipoEleccionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmMenu(this.motor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConfigActionPerformed
                                          
        String titulo = txtTitulo.getText().trim();
        String fecha = txtFecha.getText().trim();
        
        if (cmbTipoEleccion.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un tipo de elección.");
            return;
        }
        String tipoEleccion = cmbTipoEleccion.getSelectedItem().toString();
        

        if (titulo.isEmpty() || fecha.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El título y la fecha son campos obligatorios.");
            return;
        }

        try {

            int maxActas = motor.getGestorMesas().getCantidadActual();
            

            if (maxActas == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Operación denegada: Primero debe registrar las mesas electorales en el sistema.");
                return;
            }

            Eleccion nuevaEleccion = null;

            if (tipoEleccion.equals("Referéndum")) {
                
                nuevaEleccion = new Referendum(titulo, fecha, maxActas); 
                
            } else { 
                
                int maxCandidatos = motor.getGestorCandidatos().getCantidadActual();
                

                if (maxCandidatos == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Operación denegada: Primero debe inscribir a los candidatos en el sistema.");
                    return;
                }
                
                nuevaEleccion = new EleccionMunicipal(titulo, fecha, maxActas, maxCandidatos);
            }


            motor.getGestorElecciones().registrarEleccion(nuevaEleccion);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Elección '" + titulo + "' configurada con éxito.\nMesas habilitadas: " + maxActas);
            

            new frmMenu(this.motor).setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error interno al configurar la elección: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnGuardarConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarInterfazInicial() {

        cmbTipoEleccion.removeAllItems();
        cmbTipoEleccion.addItem("Municipal");
        cmbTipoEleccion.addItem("Nacional");
        cmbTipoEleccion.addItem("Referéndum");
        
        
    }
    
    private void llenarComboTipoEleccion() {

    cmbTipoEleccion.removeAllItems(); 
    cmbTipoEleccion.addItem("Municipal");
    cmbTipoEleccion.addItem("Nacional");
    cmbTipoEleccion.addItem("Referéndum");
    cmbTipoEleccion.setSelectedIndex(0); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarConfig;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbTipoEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
