/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.*;
import modelo.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmCandidatos extends javax.swing.JFrame {
    private LogicaElectoral motor;
    

    /**
     * Creates new form frmCandidatos
     */
    public frmCandidatos(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        this.setLocationRelativeTo(null);
        
        llenarComboPartidos();
        actualizarTablaCandidatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbPartidos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCandidatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        cmbPartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPartidosActionPerformed(evt);
            }
        });

        tblCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "DNI", "Partido Politico"
            }
        ));
        tblCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCandidatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCandidatos);

        jLabel3.setText("Partido Politico");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre)
                        .addComponent(txtDni)
                        .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnVolver)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String dni = txtDni.getText().trim();
    int indexPartido = cmbPartidos.getSelectedIndex();

    if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty() || indexPartido == -1) {
        JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios.");
        return;
    }

    PartidoPolitico partidoSeleccionado = motor.getGestorPartidos().getBdPartidos()[indexPartido];

    
    boolean exito = motor.getGestorCandidatos().registrarCandidato(nombre, apellido, dni,partidoSeleccionado);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Candidato " + apellido + " registrado correctamente.");
        actualizarTablaCandidatos();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo registrar (Arreglo lleno o DNI duplicado).");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void cmbPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPartidosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       new frmMenu(this.motor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblCandidatos.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un candidato de la tabla");
            return;
        }

        Object objDni = tblCandidatos.getValueAt(fila, 2);
        if (objDni == null) return; 

        String dni = objDni.toString();

        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Seguro que deseas sacar de la contienda al candidato con DNI " + dni + "?", 
            "Confirmación", JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            boolean exito = motor.getGestorCandidatos().eliminarCandidato(dni);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Candidato eliminado con éxito.");
                actualizarTablaCandidatos();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontró el DNI en el registro.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCandidatosMouseClicked
        int fila = tblCandidatos.getSelectedRow();
        if (fila != -1) {
            Object objNombre = tblCandidatos.getValueAt(fila, 0);
            Object objApellido = tblCandidatos.getValueAt(fila, 1);
            Object objDni = tblCandidatos.getValueAt(fila, 2);
            Object objPartido = tblCandidatos.getValueAt(fila, 3);

            txtNombre.setText(objNombre != null ? objNombre.toString() : "");
            txtApellido.setText(objApellido != null ? objApellido.toString() : "");
            txtDni.setText(objDni != null ? objDni.toString() : "");
            

            if (objPartido != null) {
                cmbPartidos.setSelectedItem(objPartido.toString());
            }
        }
               
                
    }//GEN-LAST:event_tblCandidatosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String dni = txtDni.getText().trim();
        String nuevosNombres = txtNombre.getText().trim();
        String nuevosApellidos = txtApellido.getText().trim();

        if (dni.isEmpty() || nuevosNombres.isEmpty() || nuevosApellidos.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios.");
            return;
        }

        Candidato candidato = motor.getGestorCandidatos().buscarPorDni(dni);

        if (candidato != null) {
            candidato.setNombres(nuevosNombres);
            candidato.setApellidos(nuevosApellidos);
            
            // Si también modificas el partido desde un ComboBox:
            // PartidoPolitico nuevoPartido = motor.getGestorPartidos().buscarPorSigla(cmbPartidos.getSelectedItem().toString());
            // candidato.setPartido(nuevoPartido);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Candidato modificado con éxito.");
            
            txtDni.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            
            actualizarTablaCandidatos(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se puede modificar el DNI");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void llenarComboPartidos() {
        // 1. Limpiamos el combo por si acaso
        cmbPartidos.removeAllItems();
        
        // 2. Traemos la lista de partidos desde el backend
        PartidoPolitico[] partidos = motor.getGestorPartidos().getBdPartidos();
        int total = motor.getGestorPartidos().getCantidadActual();
        
        // 3. Llenamos el combo solo con los nombres
        for (int i = 0; i < total; i++) {
            cmbPartidos.addItem(partidos[i].getNombre());
        }
    }
    
    private void actualizarTablaCandidatos() {
    DefaultTableModel modelo = (DefaultTableModel) tblCandidatos.getModel();
    modelo.setRowCount(0);

    Candidato[] lista = motor.getGestorCandidatos().getBdCandidatos();
    int total = motor.getGestorCandidatos().getCantidadActual();

    for (int i = 0; i < total; i++) {
        Object[] fila = {
            lista[i].getNombres(),
            lista[i].getApellidos(), // <--- No olvides el getter del apellido
            lista[i].getDni(),
            lista[i].getPartido().getNombre()
        };
        modelo.addRow(fila);
    }
}
    
    private void limpiarCampos() {
    txtNombre.setText("");
    txtApellido.setText("");
    txtDni.setText("");
    txtNombre.requestFocus(); // Pone el cursor listo para el siguiente
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbPartidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblCandidatos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
