/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.*;
import modelo.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class frmDetalleMesa extends javax.swing.JFrame {
    private LogicaElectoral motor;
    private String idMesaActual; 
    private frmMesas ventanaPadre; 

    /**
     * Creates new form frmDetalleMesa
     */
    public frmDetalleMesa(LogicaElectoral motor, String idMesa,frmMesas padre) {
        initComponents();
        this.motor = motor;
        this.idMesaActual = idMesa;
        this.ventanaPadre = padre; 
        this.setLocationRelativeTo(null);
        
        
        this.setTitle("Administrando Miembros - Mesa: " + idMesaActual);
        
       
        llenarComboCargos(); 
        actualizarTablaMiembros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarMiembro = new javax.swing.JButton();
        btnEliminarMiembro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMiembros = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarMiembro.setText("Agregar Miembro");
        btnAgregarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMiembroActionPerformed(evt);
            }
        });

        btnEliminarMiembro.setText("Eliminar Miembro");
        btnEliminarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMiembroActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Dni");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cargo");

        tblMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Cargo"
            }
        ));
        tblMiembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMiembrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMiembros);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtApellido)
                                    .addComponent(txtDni)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarMiembro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarMiembro)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMiembro)
                    .addComponent(btnEliminarMiembro)
                    .addComponent(btnVolver)
                    .addComponent(btnModificar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMiembroActionPerformed
       String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String dni = txtDni.getText().trim();
    
   
    if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La red está en medio, no la cruces. Llena todos los campos.");
        return;
    }

    String cargoSeleccionado = cmbCargo.getSelectedItem().toString().toUpperCase();
    TipoCargo cargoElegido = TipoCargo.valueOf(cargoSeleccionado);

    MiembroDeMesa nuevoMiembro = new MiembroDeMesa(nombre, apellido, dni, cargoElegido);

    boolean exito = motor.getGestorMesas().agregarMiembroAMesa(idMesaActual, nuevoMiembro);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Miembro asignado a la mesa " + idMesaActual);
        actualizarTablaMiembros();
    } else {
        JOptionPane.showMessageDialog(this, "Error: La mesa está llena, el DNI se repite, o ese cargo ya está ocupado.");
    }
    }//GEN-LAST:event_btnAgregarMiembroActionPerformed

    private void btnEliminarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMiembroActionPerformed
        int fila = tblMiembros.getSelectedRow();
    
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona a quién vas a sacar de la mesa.");
        return;
    }

    Object objDni = tblMiembros.getValueAt(fila, 2);
    if (objDni == null) return; 

    String dni = objDni.toString();

    int resp = JOptionPane.showConfirmDialog(this, 
        "¿Retirar al miembro con DNI " + dni + " de la mesa " + idMesaActual + "?", 
        "Confirmar", JOptionPane.YES_NO_OPTION);
        
    if (resp == JOptionPane.YES_OPTION) {
        boolean exito = motor.getGestorMesas().eliminarMiembroDeMesa(idMesaActual, dni);
        
        if (exito) {
            actualizarTablaMiembros();

        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
    }
    }//GEN-LAST:event_btnEliminarMiembroActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventanaPadre.actualizarTablaMesas(); 
        
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String dni = txtDni.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();

        if (dni.isEmpty() || txtDni.isEditable()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un miembro dando clic en la tabla.");
            return;
        }

        if (nombre.isEmpty() || apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los nombres y apellidos no pueden estar vacíos.");
            return;
        }

        MesaElectoral mesa = motor.getGestorMesas().buscarPorId(idMesaActual);
        
        if (mesa != null) {
            MiembroDeMesa[] miembros = mesa.getMiembros();
            MiembroDeMesa miembroEncontrado = null;

            for (int i = 0; i < mesa.getContadorMiembros(); i++) {
                if (miembros[i].getDni().equals(dni)) {
                    miembroEncontrado = miembros[i];
                    break;
                }
            }

            if (miembroEncontrado != null) {
                miembroEncontrado.setNombres(nombre);
                miembroEncontrado.setApellidos(apellido);
                
                String cargoSeleccionado = cmbCargo.getSelectedItem().toString().toUpperCase();
                miembroEncontrado.setCargo(TipoCargo.valueOf(cargoSeleccionado));

                JOptionPane.showMessageDialog(this, "Miembro modificado con éxito.");

                txtNombre.setText("");
                txtApellido.setText("");
                txtDni.setText("");
                txtDni.setEditable(true);

                actualizarTablaMiembros();
            } else {
                JOptionPane.showMessageDialog(this, "Error crítico: El miembro no existe en esta mesa.");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblMiembrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMiembrosMouseClicked
        int fila = tblMiembros.getSelectedRow();
        if (fila == -1) return;

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblMiembros.getModel();

        txtNombre.setText(modelo.getValueAt(fila, 0).toString());
        txtApellido.setText(modelo.getValueAt(fila, 1).toString());
        txtDni.setText(modelo.getValueAt(fila, 2).toString());
        cmbCargo.setSelectedItem(modelo.getValueAt(fila, 3).toString());

        txtDni.setEditable(false);
    }//GEN-LAST:event_tblMiembrosMouseClicked

    private void actualizarTablaMiembros() {
    DefaultTableModel modelo = (DefaultTableModel) tblMiembros.getModel();
    modelo.setRowCount(0);

    MesaElectoral mesa = motor.getGestorMesas().buscarPorId(idMesaActual);
    
    if (mesa == null) return; 

    MiembroDeMesa[] miembros = mesa.getMiembros();
    int totalMiembros = mesa.getContadorMiembros();

    for (int i = 0; i < totalMiembros; i++) {
        Object[] fila = {
            miembros[i].getNombres(),
            miembros[i].getApellidos(),
            miembros[i].getDni(),
            miembros[i].getCargo().name()
        };
        modelo.addRow(fila);
    }
}
    
    private void llenarComboCargos() {
        cmbCargo.removeAllItems(); 
        
        for (TipoCargo cargo : TipoCargo.values()) {
            cmbCargo.addItem(cargo.name()); 
        }
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMiembro;
    private javax.swing.JButton btnEliminarMiembro;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMiembros;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
