/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.*;

public class frmMenu extends javax.swing.JFrame {
    private LogicaElectoral motor;

    /**
     * Creates new form frmMenu
     */
    public frmMenu(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        this.setLocationRelativeTo(null);
        lblBienvenida.setText("Bienvenido: " + motor.getGestorAuth().getOperadorActual().getNombres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPartidos = new javax.swing.JButton();
        btnCandidatos = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnElecciones = new javax.swing.JButton();
        btnVotacion = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPartidos.setText("Gestion de Partidos");
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });

        btnCandidatos.setText("Gestion de Candidatos");
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });

        btnMesas.setText("Mesas y Miembros");
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });

        btnElecciones.setText("Configurar Elecciones");
        btnElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionesActionPerformed(evt);
            }
        });

        btnVotacion.setText("Registro de Actas");
        btnVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotacionActionPerformed(evt);
            }
        });

        btnResultados.setText("Escrutinio y Reportes");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        lblBienvenida.setText("_");

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPartidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnElecciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVotacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPartidos)
                .addGap(18, 18, 18)
                .addComponent(btnCandidatos)
                .addGap(18, 18, 18)
                .addComponent(btnMesas)
                .addGap(18, 18, 18)
                .addComponent(btnElecciones)
                .addGap(18, 18, 18)
                .addComponent(btnVotacion)
                .addGap(18, 18, 18)
                .addComponent(btnResultados)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        frmPartidos ventanaPartidos = new frmPartidos(this.motor);
        ventanaPartidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPartidosActionPerformed

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
        frmCandidatos ventanaCandidatos = new frmCandidatos(this.motor);
        ventanaCandidatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCandidatosActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        frmLogin login = new frmLogin(this.motor);
        login.setVisible(true);
    
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        frmMesas ventanaMesas = new frmMesas(this.motor);
        ventanaMesas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotacionActionPerformed
        frmVotacion ventanaVotacion= new frmVotacion(this.motor);
        ventanaVotacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVotacionActionPerformed

    private void btnEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionesActionPerformed
        frmConfigurarEleccion ventanaConfig = new frmConfigurarEleccion(this.motor);
        ventanaConfig.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEleccionesActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        frmReportes ventanaReportes= new frmReportes(this.motor);
        ventanaReportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnResultadosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnElecciones;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnVotacion;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
