/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import logica.LogicaElectoral;
import modelo.*;
import javax.swing.table.DefaultTableModel;


public class frmPartidos extends javax.swing.JFrame {
        private LogicaElectoral motor;


    /**
     * Creates new form frmPartidos
     */
    public frmPartidos(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        this.setLocationRelativeTo(null);
        actualizarTabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarAction = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtSiglas = new javax.swing.JTextField();
        txtLider = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartidos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnEliminarPartido = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardarAction.setText("Guardar");
        btnGuardarAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionActionPerformed(evt);
            }
        });

        txtLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiderActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Siglas");

        jLabel3.setText("R.Legal");

        tblPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Siglas", "R.Legal"
            }
        ));
        tblPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPartidos);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEliminarPartido.setText("Eliminar");
        btnEliminarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPartidoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnGuardarAction, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(txtLider)
                        .addComponent(txtSiglas)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnModificar)
                                .addComponent(btnGuardarAction)
                                .addComponent(btnEliminarPartido)))))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionActionPerformed
    String nombre = txtNombre.getText().trim();
    String siglas = txtSiglas.getText().trim();
    String lider = txtLider.getText().trim();

    if (nombre.isEmpty() || siglas.isEmpty() || lider.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No dejes campos vacíos, ingeniero.");
        return;
    }

    PartidoPolitico nuevo = new PartidoPolitico(nombre, siglas, "sin_logo.png", lider);
    boolean exito = motor.getGestorPartidos().registrarPartido(nuevo);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Partido registrado con éxito.");
        actualizarTabla(); 
        limpiarCampos();   
    } else {
        JOptionPane.showMessageDialog(this, "Error: El arreglo está lleno o el partido ya existe.");
    }
    }//GEN-LAST:event_btnGuardarActionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmMenu(this.motor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPartidoActionPerformed
    int filaSeleccionada = tblPartidos.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Primero selecciona un partido de la tabla, ingeniero.");
        return;
    }

    String siglas = tblPartidos.getValueAt(filaSeleccionada, 1).toString();

    int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el partido " + siglas + "?", "Confirmación", JOptionPane.YES_NO_OPTION);
    
    if (respuesta == JOptionPane.YES_OPTION) {
        boolean exito = motor.getGestorPartidos().eliminarPartido(siglas);
        
        if (exito) {
            actualizarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar. Revisa tu backend.");
        }
    }
    }//GEN-LAST:event_btnEliminarPartidoActionPerformed

    private void tblPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPartidosMouseClicked
        int fila = tblPartidos.getSelectedRow();
    if (fila != -1) {
        txtNombre.setText(tblPartidos.getValueAt(fila, 0).toString());
        txtSiglas.setText(tblPartidos.getValueAt(fila, 1).toString());
        txtLider.setText(tblPartidos.getValueAt(fila, 2).toString());
    }
    }//GEN-LAST:event_tblPartidosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String sigla = txtSiglas.getText().trim();
        String nuevoNombre = txtNombre.getText().trim();
        String nuevoRepresentante = txtLider.getText().trim();

        if (sigla.isEmpty() || nuevoNombre.isEmpty() || nuevoRepresentante.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos antes de modificar.");
            return;
        }

        PartidoPolitico partido = motor.getGestorPartidos().buscarPorSigla(sigla);

        if (partido != null) {
            partido.setNombre(nuevoNombre);
            partido.setRepresentanteLegal(nuevoRepresentante);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Partido modificado con éxito.");
            
            txtSiglas.setText("");
            txtNombre.setText("");
            txtLider.setText("");
            
            actualizarTabla(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pueden modificar las siglas.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLiderActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void actualizarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tblPartidos.getModel();
    
    modelo.setRowCount(0);
    
    PartidoPolitico[] lista = motor.getGestorPartidos().getBdPartidos();
    int total = motor.getGestorPartidos().getCantidadActual();
    
    for (int i = 0; i < total; i++) {
        Object[] fila = {
            lista[i].getNombre(),
            lista[i].getSigla(),
            lista[i].getRepresentanteLegal()
        };
        modelo.addRow(fila);
    }
    
}
    private void limpiarCampos() {
    txtNombre.setText("");
    txtSiglas.setText("");
    txtLider.setText("");
    txtNombre.requestFocus(); 
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPartido;
    private javax.swing.JButton btnGuardarAction;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPartidos;
    private javax.swing.JTextField txtLider;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSiglas;
    // End of variables declaration//GEN-END:variables
}
