/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JOptionPane;
import logica.LogicaElectoral;
import modelo.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class frmReportes extends javax.swing.JFrame {
    private LogicaElectoral motor;
    
    

    /**
     * Creates new form frmReportes
     */
    public frmReportes(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        
        this.setLocationRelativeTo(null); 
        
        txtAreaReporte.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReporte = new javax.swing.JTextArea();
        btnProcesar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnReporteMesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaReporte.setColumns(20);
        txtAreaReporte.setRows(5);
        jScrollPane1.setViewportView(txtAreaReporte);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnReporteMesas.setText("Reporte de Mesas");
        btnReporteMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProcesar)
                .addGap(18, 18, 18)
                .addComponent(btnReporteMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnVolver)
                    .addComponent(btnReporteMesas))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmMenu(this.motor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        Eleccion activa = motor.getGestorElecciones().getEleccionActiva();
        
        if (activa == null) {
            txtAreaReporte.setText("Error: No hay ninguna elección configurada en el sistema.");
            return;
        }

        activa.realizarConteoAutomático();

        String textoResultado = activa.generarReporteResultados();

        txtAreaReporte.setText(textoResultado);
    
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnReporteMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMesasActionPerformed
        Eleccion activa = motor.getGestorElecciones().getEleccionActiva();
        
        if (activa == null) {
            txtAreaReporte.setText("Error: No hay elección configurada.");
            return;
        }

        if (activa instanceof EleccionMunicipal) {
            EleccionMunicipal eleccionMuni = (EleccionMunicipal) activa;
            String textoDetallado = eleccionMuni.generarReporteDetalladoPorMesas();
            txtAreaReporte.setText(textoDetallado);
        } else {
            txtAreaReporte.setText("El reporte detallado con votos preferenciales aplica para Elecciones Municipales/Nacionales.");
        }
    }//GEN-LAST:event_btnReporteMesasActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnReporteMesas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReporte;
    // End of variables declaration//GEN-END:variables
}
