/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JOptionPane;
import logica.LogicaElectoral;
import modelo.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class frmVotacion extends javax.swing.JFrame {
    private LogicaElectoral motor;

    /**
     * Creates new form frmVotacion
     */
    public frmVotacion(LogicaElectoral motor) {
        initComponents();
        this.motor = motor;
        this.setLocationRelativeTo(null);
        
        cargarMesasDisponibles();
        prepararTablaDeVotos();
    }
    
    private void cargarMesasDisponibles() {
        cmbMesas.removeAllItems(); 
        
        int totalMesas = motor.getGestorMesas().getCantidadActual();
        MesaElectoral[] mesas = motor.getGestorMesas().getBdMesas();
        
        for (int i = 0; i < totalMesas; i++) {
            cmbMesas.addItem(mesas[i].getIdMesa());
        }
    }
    
    private void prepararTablaDeVotos() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblVotos.getModel();
        modelo.setRowCount(0); 

        Eleccion eleccionActiva = motor.getGestorElecciones().getEleccionActiva();

        if (eleccionActiva instanceof EleccionMunicipal) {
            
            int totalCandidatos = motor.getGestorCandidatos().getCantidadActual();
            Candidato[] candidatos = motor.getGestorCandidatos().getBdCandidatos();
            
            for (int i = 0; i < totalCandidatos; i++) {
                String nombreCompleto = candidatos[i].getNombres() + " " + candidatos[i].getApellidos();
                modelo.addRow(new Object[]{nombreCompleto, "0"}); 
            }
            
        } else if (eleccionActiva instanceof Referendum) {
            
            modelo.addRow(new Object[]{"SÍ", "0"});
            modelo.addRow(new Object[]{"NO", "0"});
            
        }

        txtBlancos.setText("0");
        txtNulos.setText("0");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMesas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBlancos = new javax.swing.JTextField();
        txtNulos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVotos = new javax.swing.JTable();
        btnGuardarActa = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Mesa");

        jLabel2.setText("En Blanco");

        txtNulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNulosActionPerformed(evt);
            }
        });

        jLabel3.setText("Nulos");

        tblVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Opción / Candidato", "Votos"
            }
        ));
        jScrollPane1.setViewportView(tblVotos);

        btnGuardarActa.setText("Guardar Acta");
        btnGuardarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNulos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarActa)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarActa)
                    .addComponent(btnVolver))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNulosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new frmMenu(this.motor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActaActionPerformed
        try {
            if (cmbMesas.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una mesa válida.");
                return;
            }
            String idMesa = cmbMesas.getSelectedItem().toString();
            Eleccion eleccionActiva = motor.getGestorElecciones().getEleccionActiva();

            if (eleccionActiva == null) return;

            MesaElectoral mesaActual = null;
            int totalMesas = motor.getGestorMesas().getCantidadActual();
            MesaElectoral[] bdMesas = motor.getGestorMesas().getBdMesas();
            
            for (int i = 0; i < totalMesas; i++) {
                if (bdMesas[i].getIdMesa().equals(idMesa)) {
                    mesaActual = bdMesas[i];
                    break;
                }
            }

            int blancos = Integer.parseInt(txtBlancos.getText().trim());
            int nulos = Integer.parseInt(txtNulos.getText().trim());
            int votosTabla = 0;

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblVotos.getModel();
            int filasTotales = modelo.getRowCount();

            for (int i = 0; i < filasTotales; i++) {
                votosTabla += Integer.parseInt(modelo.getValueAt(i, 1).toString());
            }

            int efectivos = votosTabla + blancos + nulos;
            int registrados = 300; 
            String numActa = "ACT-" + mesaActual.getIdMesa();
            java.time.LocalDateTime fechaHora = java.time.LocalDateTime.now();
            
            ActaElectoral nuevaActa = new ActaElectoral(
                numActa, 
                "Acta de " + eleccionActiva.getClass().getSimpleName(), 
                fechaHora, 
                "Sede Central", 
                mesaActual, 
                filasTotales, 
                registrados, 
                efectivos
            );

            if (eleccionActiva instanceof EleccionMunicipal) {
                
                Candidato[] bdCandidatos = motor.getGestorCandidatos().getBdCandidatos();
                int totalCandidatos = motor.getGestorCandidatos().getCantidadActual();

                for (int i = 0; i < filasTotales; i++) {
                    String nombreEnTabla = modelo.getValueAt(i, 0).toString();
                    int cantidadVotos = Integer.parseInt(modelo.getValueAt(i, 1).toString());

                    Candidato candEncontrado = null;
                    for (int j = 0; j < totalCandidatos; j++) {
                        String nombreCompleto = bdCandidatos[j].getNombres() + " " + bdCandidatos[j].getApellidos();
                        if (nombreCompleto.equals(nombreEnTabla)) {
                            candEncontrado = bdCandidatos[j];
                            break;
                        }
                    }

                    if (candEncontrado != null) {
                        DetalleVoto detalle = new DetalleVoto(candEncontrado, cantidadVotos, 0);  
                        nuevaActa.agregarResultado(detalle); 
                    }
                }
            } else if (eleccionActiva instanceof Referendum) {
                int votosSi = Integer.parseInt(modelo.getValueAt(0, 1).toString());
                int votosNo = Integer.parseInt(modelo.getValueAt(1, 1).toString());

                nuevaActa.agregarResultado(new DetalleVoto(null, votosSi, 0));
                nuevaActa.agregarResultado(new DetalleVoto(null, votosNo, 0));
            }

            boolean exito = eleccionActiva.registrarActa(nuevaActa);

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Acta procesada correctamente. Total votos: " + efectivos);
                cmbMesas.removeItem(idMesa); 
                txtBlancos.setText("0");
                txtNulos.setText("0");
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    modelo.setValueAt("0", i, 1);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo registrar el acta (Límite alcanzado).");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Asegúrese de que todos los votos (incluso blancos y nulos) sean números enteros.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
              
    }//GEN-LAST:event_btnGuardarActaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarActa;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVotos;
    private javax.swing.JTextField txtBlancos;
    private javax.swing.JTextField txtNulos;
    // End of variables declaration//GEN-END:variables
}
